apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid19analysis
  labels:
    app: covid19analysis
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: covid19analysis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: covid19analysis
    spec:
      containers:
        - image: greentropikal/covid19_analysis
          imagePullPolicy: Always
          name: covid19analysis
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: covid19analysis
  labels:
    app: covid19analysis
spec:
  type: LoadBalancer
  selector:
    app: covid19analysis
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
