apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid19-analysis
  labels:
    app: covid19-analysis
  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: covid19-analysis
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: covid19-analysis
    spec:
      containers:
        - image: greentropikal/covid19-analysis
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          imagePullPolicy: Always
          name: covid19-analysis
          env:
        - name: VERSION_INFO
          value: "VERSION_INFO_VALUE"
        - name: BUILD_DATE
          value: "BUILD_DATE_VALUE"
          ports:
            - containerPort: 80