---
apiVersion: v1
kind: Service
metadata:
  name: covid19-analysis
  labels:
    app: covid19-analysis
spec:
  type: LoadBalancer
  selector:
    app: covid19-analysis
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP