apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid19-analysis
  labels:
    app: covid19-analysis
  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: covid19-analysis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: covid19-analysis
    spec:
      containers:
        - image: ${AWS_ECR_URL}/${REPO_NAME}:${CIRCLE_SHA1}
          imagePullPolicy: Always
          name: covid19-analysis
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: covid19-analysis
  labels:
    app: covid19-analysis
spec:
  type: LoadBalancer
  selector:
    app: covid19-analysis
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP