apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid19-analysis
  labels:
    app: covid19-analysis
  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: covid19analysis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: covid19analysis
    spec:
      containers:
        - image: greentropikal/covid19-analysis:v.1.1
          imagePullPolicy: Always
          name: covid19analysis
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
         
